server:
  port: 8081
spring:
  application:
    name: userIceBoxCheck

  datasource:
    url: jdbc:postgresql://localhost:5432/Users_db
    username: postgres
    password: 100891

  cloud:
    openfeign:
      client:
        config:
          recipe-service:
            url: http://localhost:8080

#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/mydatabase
#    username: user
#    password: password
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#  jpa:
#    hibernate:
#      ddl-auto: update
#  profiles:
#    active: dev
#
#logging:
#  level:
#    root: INFO
#
#server:
#  port: 8080
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
